# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fine Untitled
subtitle: seek perspective, not perfection
email: monica.wojciechowski@gmail.com
description: you are loved because you are, not because you are someone
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://fineuntitled.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  monicawoj
date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
#remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
logo: "/images/fine-untitled-logo.png"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Monica Wojciechowski
#  picture: /images/michael-rose-photo.jpg
  email: fineuntitled@gmail.com
#  twitter: mmistakes
  links:
#    - title: Twitter
#      url: https://twitter.com/mmistakes
#      icon: fab fa-twitter-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/monicawojciechowski/
      icon: fab fa-linkedin
    - title: GitHub
      url: https://github.com/monicawoj
      icon: fab fa-github-square

# Footer Links
footer_links:
#  - title: Twitter
#    url: https://twitter.com/mmistakes
#    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/monicawojciechowski/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/monicawoj
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

#Copyright
copyright: "&copy; 2018. Monica Wojciechowski. Fine Untitled."